version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres.iyktdlxvhfvsazbomanx
      - POSTGRES_PASSWORD=i9SvnosxJCCrtXwg
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres.iyktdlxvhfvsazbomanx" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=your_redis_password
    command: redis-server --requirepass "$$REDIS_PASSWORD"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD PING" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres.iyktdlxvhfvsazbomanx
      - DB_PASSWORD=i9SvnosxJCCrtXwg
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_PASSWORD=your_redis_password
      - REDIS_HOST=redis
      - SECRET_KEY=your_secret_key
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: daphne -p 8000 ryderbackend.asgi:application
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8000/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
