# Generated by Django 5.1.2 on 2024-10-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('api', '0001_initial'),
  ]

  operations = [
    migrations.AlterField(
      model_name='trip',
      name='destinationLat',
      field=models.CharField(max_length=50),
    ),
    migrations.AlterField(
      model_name='trip',
      name='destinationLong',
      field=models.CharField(max_length=50),
    ),
    migrations.AlterField(
      model_name='trip',
      name='startedFromLat',
      field=models.CharField(max_length=50),
    ),
    migrations.AlterField(
      model_name='trip',
      name='startedFromLong',
      field=models.CharField(max_length=50),
    ),
    migrations.AlterField(
      model_name='trip',
      name='tripStatus',
      field=models.CharField(choices=[('waiting_for_passenger', 'Waiting for Passenger'), ('completed', 'Completed'),
                                      ('rejected', 'Rejected'), ('way_to_pick_up', 'Way to Pick Up'),
                                      ('cancelled', 'Cancelled'), ('way_to_drop_off', 'Way to Drop Off')],
                             default='way_to_pick_up', max_length=50),
    ),
  ]
